CREATE TABLE IF NOT EXISTS users (
  id SERIAL PRIMARY KEY,
  username VARCHAR(50) NOT NULL UNIQUE,
  password VARCHAR(50) NOT NULL,
  coins INT DEFAULT 0,
  elo INT DEFAULT 0
);


CREATE TABLE IF NOT EXISTS decks (
id SERIAL PRIMARY KEY,
cardid SERIAL FOREIGN KEY,
userid SERIAL FOREIGN KEY);

CREATE TABLE IF NOT EXISTS stacks (
id SERIAL PRIMARY KEY,
cardid SERIAL FOREIGN KEY,
userid SERIAL FOREIGN KEY);

CREATE TABLE IF NOT EXISTS trades (
id SERIAL PRIMARY KEY,
cardid SERIAL FOREIGN KEY,
userid SERIAL FOREIGN KEY);

CREATE TABLE IF NOT EXISTS packages (
id SERIAL PRIMARY KEY,
cardid SERIAL FOREIGN KEY);

CREATE TABLE IF NOT EXISTS cards (
id VARCHAR(255) PRIMARY KEY,
name VARCHAR(50) NOT NULL,
damage FLOAT(24) ,
element VARCHAR(50) NOT NULL,
cardtype VARCHAR(50) NOT NULL, 
monstertype VARCHAR(50));





